services:


  wc: 
    build:
      context: .
      args:
        - REGION=wc
        - REGION_NAME=Western Cape
        - PORT=5000
    ports:
      - 5000:5000
    volumes:
      - ./server_files/shared_private/wc:/flask-app/server_files/shared_private
      - ./server_files/shared_private/global/gtfs-validation-6.0.0-cli.jar:/flask-app/server_files/shared_private/gtfs-validation-6.0.0-cli.jar
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379 
      REDIS_DB: 0

  durb: 
    build:
      context: .
      args:
        - REGION=durb
        - REGION_NAME=Durban
        - PORT=5002
    ports:
      - 5002:5000
    volumes:
      - ./server_files/shared_private/global/gtfs-validation-6.0.0-cli.jar:/flask-app/server_files/shared_private/gtfs-validation-6.0.0-cli.jar
      - ./server_files/shared_private/durb:/flask-app/server_files/shared_private
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379 
      REDIS_DB: 1

  gaut:
    build:
      context: .
      args:
        - REGION=gaut
        - REGION_NAME=Gauteng
        - PORT=5001
    ports:
      - 5001:5000
    volumes:
      - ./server_files/shared_private/gaut:/flask-app/server_files/shared_private
      - ./server_files/shared_private/global:/flask-app/server_files/shared_private/global
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379 
      REDIS_DB: 2



  redis_db:
    image:
      "redis"
    ports:
      - 6379:6379
  
  reverse-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "reverse-proxy"
    volumes:
        - "./nginx_conf/certs:/etc/nginx/certs:ro"
        - "./nginx_conf/html:/var/www/html:rw"
        - "./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./server_files/shared_private/:/var/log/nginx/"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    ports:
        - "80:80"
        - "443:443"