services:
  flask:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./server_files/static/shared:/server_files/static/shared
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379 
      C_FORCE_ROOT: "true"

  redis_db:
    image:
      "redis"
    ports:
      - 6379:6379
