services:
  flask:
    build: .
    ports:
      - 443:5000
    volumes:
      - ./server_files/static/shared:/flask-app/server_files/static/shared
      - ./server_files/shared_private:/flask-app/server_files/shared_private
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379 
      C_FORCE_ROOT: "true"
  redis_db:
    image:
      "redis"
    ports:
      - 6379:6379