services:
  flask:
    build: .
    ports:
      - 443:5000
    volumes:
      - ./server_files/static/shared:/server_files/static/shared
      - ./server_files/shared_private:/server_files/shared_private
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379 
      C_FORCE_ROOT: "true"
    depends_on:
      - redis_db

  redis_db:
    image:
      "redis"
    ports:
      - 6379:6379
